// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLvhZJUmJaxPj7bA3DyHY67gqZPCTjFsU',
    appId: '1:1009072881450:web:c9b789bafaff183e906853',
    messagingSenderId: '1009072881450',
    projectId: 'megboss',
    authDomain: 'megboss.firebaseapp.com',
    storageBucket: 'megboss.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBck0DlITuOOIlcsEPpzHhWVpXLhtv4dKg',
    appId: '1:1009072881450:android:f59af41acd8b1b2d906853',
    messagingSenderId: '1009072881450',
    projectId: 'megboss',
    storageBucket: 'megboss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC23Si4r4zTs50SzNF1oh7oJRGEkWbeAgE',
    appId: '1:1009072881450:ios:0f46c148cc7fa4a4906853',
    messagingSenderId: '1009072881450',
    projectId: 'megboss',
    storageBucket: 'megboss.firebasestorage.app',
    iosBundleId: 'com.example.megaboss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC23Si4r4zTs50SzNF1oh7oJRGEkWbeAgE',
    appId: '1:1009072881450:ios:0f46c148cc7fa4a4906853',
    messagingSenderId: '1009072881450',
    projectId: 'megboss',
    storageBucket: 'megboss.firebasestorage.app',
    iosBundleId: 'com.example.megaboss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLvhZJUmJaxPj7bA3DyHY67gqZPCTjFsU',
    appId: '1:1009072881450:web:5195155b414769b1906853',
    messagingSenderId: '1009072881450',
    projectId: 'megboss',
    authDomain: 'megboss.firebaseapp.com',
    storageBucket: 'megboss.firebasestorage.app',
  );
}
